export const REQUEST_LOGIN_STATUS = 'REQUEST_LOGIN_STATUS';
export const RECEIVE_LOGIN_SUCCESS = 'RECEIVE_LOGIN_SUCCESS';
export const RECEIVE_LOGIN_FAILURE = 'RECEIVE_LOGIN_FAILURE';
export const RECEIVE_FB_USER_DATA = 'RECEIVE_FB_USER_DATA';
export const RECEIVE_FB_USER_ID = 'RECEIVE_FB_USER_ID';
export const RECEIVE_FRIEND_LIST = 'RECEIVE_FRIEND_LIST';
export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';

export const REQUEST_CHAT_LIST_SUCCESS = 'REQUEST_CHAT_LIST_SUCCESS';
export const REQUEST_CHAT_LIST_FAILURE = 'REQUEST_CHAT_LIST_FAILURE';

export const REQUEST_CHAT_ROOM_SUCCESS = 'REQUEST_CHAT_ROOM_SUCCESS';

export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAILURE = 'CREATE_CHAT_FAILURE';
export const UPDATE_CURRENT_CHATROOM = 'UPDATE_CURRENT_CHATROOM';

export const RECEIVE_FRIEND_ONLINE = 'RECEIVE_FRIEND_ONLINE';

export const CREATE_CHAT_MESSAGE = 'CREATE_CHAT_MESSAGE';
